### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [goosey-goose/CODENAME-KETCHUP#1]
Hello! 

I am reviewing all group's wikis today and wanted to drop a few things here that I would like y'all to take care of.

## General
- [x] Add links to all wiki pages on the `home` page.

## Feature List
- [x] Add an indent (I believe it's 3 spaces for markdown files) for your bullet points to properly nest them under your numbered list.

## Schema
- [x] If you have an image of your db diagram, add that to your repo so that you can embed the image in your Schema page. It always looks nice to include that!

Once these are taken care of, please drop your responses/updates here as a response to this issue.

Thanks, y'all!!
Ed

**Comment by deardaveed** [comment]
all 3 issues above have been addressed and updated on our wiki
